name: Reusable Lambda Deploy Workflow

on:
  workflow_call:  # This defines it as a reusable workflow
    inputs:
      environment:
        required: true
        type: string
      role-name:
        required: true
        type: string
      function-name:
        required: true
        type: string

jobs:
  deploy:
    name: Build Lambda
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repo  
        uses: actions/checkout@v4

      - name: Use Node.js 12.0
        uses: actions/setup-node@v1
        with:
          node-version: '12.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-name }}
          aws-region: us-east-2


      - name: serverless deploy
        uses: 
        with:
          args: deploy. --stage ${{ inputs.environment }}
        env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
