on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: [development, test, staging]

    uses: ./.github/workflows/lambda_deploy.yml
    with:
      role-name: arn:aws:iam::739153323366:role/Role
      function_name: gh_test
      environment: ${{ matrix.environment }}
